### ISSUE TITLE
TechEmpower Framework Benchmarks

### ISSUE THREAD

**Issue by mit-73** [unger1984/dia#1]
Maybe add your framework to [FrameworkBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks) so you can compare its performance?

**Comment by unger1984** [comment]
This is not a framework, it is a library that can only handle http requests. It does not have a database function or other extensions. Do you really think that it should be added to FrameworkBenchmarks?

**Comment by mit-73** [comment]
@unger1984 FrameworkBenchmarks also has non-frameworks. I think for an alternative to what's out there, your library will also work (maybe even compete).

**Comment by unger1984** [comment]
PR for adding Dia to the FrameworkBenchmarks has been created https://github.com/TechEmpower/FrameworkBenchmarks/pull/6520
