### ISSUE TITLE
Compilation support?

### ISSUE THREAD

**Issue by dafanasiev** [unger1984/dia#2]
```sh
$>dart --version
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "linux_x64"

$>dart compile exe bin/example.dart 
Info: Compiling with sound null safety

error: import of dart:mirrors is not supported in the current Dart runtime

Error: AOT compilation failed
Generating AOT snapshot failed!
```

**Comment by unger1984** [comment]
Unfortunately, at the moment Dia only supports execution in JIT mode. I am working on it, maybe in the next versions it will be possible to fix it

**Comment by unger1984** [comment]
It was possible to get rid of dart:mirror, but with small, breaking api changes. Dia 0.1.0 now works in AOT mode, but has a slightly different constructor in the case of a custom Context. For standard cases, nothing and
